name: CI

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: gem

jobs:
  core:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          working-directory: gem
          bundler-cache: true
        env:
          BUNDLE_WITHOUT: active_record:development:quality

      - name: Core Minitest
        run: bundle exec ruby -Ilib:test test/test_amount.rb
        env:
          BUNDLE_WITHOUT: active_record:development:quality

      - name: Core RSpec
        run: bundle exec rspec spec/amount_rspec_matchers_spec.rb
        env:
          BUNDLE_WITHOUT: active_record:development:quality

  active_record:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.2"
          - "3.3"
          - "3.4"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          working-directory: gem
          bundler-cache: true
        env:
          BUNDLE_WITH: active_record
          BUNDLE_WITHOUT: development:quality

      - name: ActiveRecord Minitest
        run: bundle exec ruby -Ilib:test test/test_active_record.rb
        env:
          BUNDLE_WITH: active_record
          BUNDLE_WITHOUT: development:quality

      - name: ActiveRecord RSpec
        run: bundle exec rspec spec/active_record_rspec_matchers_spec.rb
        env:
          BUNDLE_WITH: active_record
          BUNDLE_WITHOUT: development:quality

  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          working-directory: gem
          bundler-cache: true
        env:
          BUNDLE_WITH: active_record:quality
          BUNDLE_WITHOUT: development

      - name: Lint
        run: bundle exec rake lint
        env:
          BUNDLE_WITH: active_record:quality
          BUNDLE_WITHOUT: development

  demo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          working-directory: demo
          bundler-cache: true

      - name: Migrate test database
        run: bin/rails db:migrate RAILS_ENV=test

      - name: Run RSpec
        run: bundle exec rspec
